version: '3.8'

services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:0.2.3
    container_name: docker-socket-proxy
    restart: unless-stopped
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - CONTAINERS=1
      - EVENTS=1
      - NETWORKS=1
      - POST=1
      - PING=1
      - INFO=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  dockflare-agent:
    image: alplat/dockflare-agent:latest
    container_name: dockflare-agent
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DOCKER_HOST=${DOCKER_HOST:-tcp://docker-socket-proxy:2375}
      - TZ=${TZ:-UTC}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - agent_data:/app/data
    depends_on:
      - docker-socket-proxy
    networks:
      - cloudflare-net

volumes:
  agent_data:

networks:
  cloudflare-net:
    name: cloudflare-net
    external: true
